language: python
python:
  - "2.7"


sudo: required
services:
  - docker

services:
    - docker

env:
    global:
        - DOCKER_VERSION=1.10.1-0~trusty


compiler:
  - gcc
  - clang

before_install:
  # list docker-engine versions
  - apt-cache madison docker-engine

  # upgrade docker-engine to specific version
  # sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}


script:
  - echo "This repo deprecated. Split up into several as this grew too large."
  - echo "So, do not use me."
  - test 1 -eq 0
  # ./scripts/build_ceed
  # docker version
  # ./scripts/build_containers
  # ./scripts/build_containers.ostro
  # docker images | grep codi | grep -q test
  # docker images | grep toolchain | grep -q test
  # docker images | grep zephyr | grep -q test
  # docker images | grep ostrobuilder | grep -q v1.0.0
  # ./scripts/run_containers
  # python tests.py

notifications:
  email:
    recipients:
    on_success: change
    on_failure: always
